# Generated by Django 3.1.2 on 2020-11-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='fecha_boleta',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='compra',
            name='hora_compra',
            field=models.TimeField(),
        ),
    ]
