# Generated by Django 3.1.2 on 2020-11-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20201112_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='nro_boleta',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compra',
            name='id_compra',
            field=models.IntegerField(default=0),
        ),
    ]
