# Generated by Django 3.1.2 on 2020-11-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20201112_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='nro_boleta',
            field=models.CharField(max_length=20),
        ),
    ]
