# Generated by Django 3.1.2 on 2020-11-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20201112_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='cant_cuota',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='compra',
            name='id_compra',
            field=models.CharField(max_length=50),
        ),
    ]
